export const KEYWORDS = [
  "diversity", "equity", "inclusion", "social justice", "diversity consciousness", "ableism", "accessibility", "accommodation",
  "accomplice", "accountability", "acculturation", "active listening", "adverse impact", "advocate", "AFAB/AMAB", "affirmative action",
  "ageism", "agency", "agender", "agent", "agnostic", "ally", "allyship", "American", "androgyne", "androgynous", "androgyny",
  "anti-blackness", "anti-racist", "anti‐Semitism", "aromantic", "asexual", "assigned sex", "assimilation", "at-risk", "autism",
  "bias", "bias incident", "bicultural", "bigotry", "BIPOC", "biphobia", "biracial", "bigender", "dual gender", "bisexual",
  "blind", "Brave Space", "capitalism", "categorization", "cisgender", "cis", "cisnormativity", "cissexism", "citizen",
  "civil rights", "civil union", "class", "classism", "climate", "closeted", "in the closet", "coalition", "code-switching",
  "codification", "collusion", "colonialism", "colonization", "color-blind", "colorism", "coming out", "conscious bias",
  "explicit bias", "co-option", "co-optation", "counter-narrative", "critical analysis", "critical media literacy", "Critical Race Theory",
  "culture", "cultural appropriation", "cultural competence", "cultural encapsulation", "cultural fluency", "cultural humility",
  "cultural landscape", "culturally responsive pedagogy", "D.A.C.A", "Deferred Action for Childhood Arrivals", "deaf", "decolonize",
  "demigender", "demisexual", "democracy", "denial", "dialogue", "disability", "diaspora", "dimensions of diversity",
  "direct threat", "disadvantaged", "discrimination", "disenfranchised", "diversity", "diversity consciousness", "diversity skills",
  "domestic partner", "dominant culture", "domination", "double consciousness", "drag queen", "king", "dysmorphism", "elitism",
  "emotional intelligence", "empathy", "enculturation", "equality", "equity", "equity (social)", "ESL", "essential functions of the job",
  "ethnicity", "ethnocentrism", "Euro-Centric", "female-bodied", "femme", "First Nation People", "feminism", "first generation",
  "fluid", "fluidity", "FTM", "F2M", "F to M", "fundamental attribution error", "fundamentalism", "gatekeeping", "gay", "gender",
  "gendered", "gender affirming surgery", "gender binary", "gender diversity", "gender dysphoria", "gender expression", "gender fluid",
  "gender identity", "gender-neutral", "gender-inclusive", "gender neutral pronouns", "gender non-conforming", "gender normative",
  "gender pronouns", "gender role", "genderqueer", "genocide", "gentrification", "glass ceiling", "global competency", "global perspective",
  "globalization", "glocalization", "group identity", "harassment", "hate crime", "HBCU", "hegemony", "heteronormativity",
  "heterosexism", "heterosexual", "heterosexual privilege", "homophobia", "homosexual", "horizontal hostility", "horizontal oppression",
  "HSI", "identity sphere", "immigrant", "implicit bias", "impostor syndrome", "in‐group bias", "favoritism", "in-groups", "out-groups",
  "inclusion", "inclusive excellence", "inclusive language", "Indigenous peoples", "institutional oppression", "intersectionality",
  "intercultural competency", "intergroup conflict", "internalized oppression", "internalized racism", "intersex", "invisible minority",
  "Islamophobia", "Ism", "justice", "Latinx", "lesbian", "LGBT", "LGBTQ", "LGBTQIAA+", "lines of difference", "linguicism", "lookism",
  "major bodily functions", "major life activities", "male-bodied", "marginalize", "marginalization", "media literacy", "microaggression",
  "micro-insults", "micro-invalidation", "minority", "minority groups", "minorities", "misogyny", "mobility", "model minority",
  "MSI", "MTF", "M2F", "M to F", "MTM", "FTF", "multicultural", "multiethnic", "multiplicity", "multiracial", "naming", "national origin",
  "nativism", "neocolonialization", "neo-liberalism", "neurodiversity", "non-binary", "gender variant", "nondisabled", "nonviolence",
  "non-white", "oppression", "oppression (institutionalized)", "oppression (internalized)", "overprivileged", "pangender", "pansexual",
  "passing privilege", "patriarchy", "Pell-eligible", "people-/person-first language", "people of color", "permanent resident",
  "personal identity", "pluralism", "post-racial", "prejudice", "privilege", "privileged group member", "pronouns", "protected status",
  "PWI", "pyramiding effect", "qualified individual", "queer", "queer theory", "questioning", "race", "racial and ethnic identity",
  "racial equity", "racial profiling", "racism", "racism (cultural)", "racism (individual)", "racism (institutional)", "racism (internalized)",
  "racism (structural)", "racist policy", "rankism", "reasonable accommodation", "reclaim", "refugee", "re-fencing", "exception-making",
  "religion", "religious oppression", "resilience", "respect", "restorative justice", "safe space", "same gender loving", "saliency",
  "sapiosexual", "scapegoating", "serostatus", "settler colonialism", "sex", "sexism", "sexual orientation", "sex assignment",
  "silencing", "sizeism", "social construction", "social forces", "social identity", "social identity development", "social inequality",
  "social justice", "social movement", "social oppression", "social self‐esteem", "social self‐view", "social transition", "socialization",
  "SOFFA", "solidarity", "spotlighting", "status (social status)", "stealth", "stereotype", "stereotype threat", "stigma",
  "stigmatization", "structural inequality", "subordination", "substantially limiting", "supremacy", "Survivor", "system of oppression",
  "TCU", "third gender", "tolerance", "tokenism", "transculturation", "transformative learning", "transgender", "transition",
  "transmisogyny", "transphobia", "transsexual", "Two Spirit", "unconscious bias", "underprivileged", "underrepresented communities",
  "underutilization", "undue hardship", "undocumented", "undocumented student", "union", "unisex", "universal design", "UPstander",
  "upward mobility", "upward social mobility", "veteran status", "white fragility", "white privilege", "white supremacy", "whiteness",
  "worldview", "xenophobia", "Yes Means Yes", "ze", "zir"
];
