export const KEYWORDS = [
  { keyword: 'anti-blackness', score: 9 },
  { keyword: 'assigned sex', score: 9 },
  { keyword: 'dual gender', score: 9 },
  { keyword: 'cisgender', score: 9 },
  { keyword: 'cis', score: 9 },
  { keyword: 'cisnormativity', score: 9 },
  { keyword: 'cissexism', score: 9 },
  { keyword: 'Critical Race Theory', score: 9 },
  { keyword: 'D.A.C.A', score: 9 },
  { keyword: 'Deferred Action for Childhood Arrivals', score: 9 },
  { keyword: 'demisexual', score: 9 },
  { keyword: 'female-bodied', score: 9 },
  { keyword: 'femme', score: 9 },
  { keyword: 'FTM', score: 9 },
  { keyword: 'F2M', score: 9 },
  { keyword: 'F to M', score: 9 },
  { keyword: 'gender affirming surgery', score: 9 },
  { keyword: 'gender binary', score: 9 },
  { keyword: 'gender diversity', score: 9 },
  { keyword: 'gender dysphoria', score: 9 },
  { keyword: 'gender expression', score: 9 },
  { keyword: 'gender fluid', score: 9 },
  { keyword: 'gender identity', score: 9 },
  { keyword: 'gender-neutral', score: 9 },
  { keyword: 'gender-inclusive', score: 9 },
  { keyword: 'gender neutral pronouns', score: 9 },
  { keyword: 'gender non-conforming', score: 9 },
  { keyword: 'gender normative', score: 9 },
  { keyword: 'gender pronouns', score: 9 },
  { keyword: 'gender role', score: 9 },
  { keyword: 'genderqueer', score: 9 },
  { keyword: 'Islamophobia', score: 9 },
  { keyword: 'male-bodied', score: 9 },
  { keyword: 'MTF', score: 9 },
  { keyword: 'M2F', score: 9 },
  { keyword: 'M to F', score: 9 },
  { keyword: 'MTM', score: 9 },
  { keyword: 'FTF', score: 9 },
  { keyword: 'non-binary', score: 9 },
  { keyword: 'gender variant', score: 9 },
  { keyword: 'pangender', score: 9 },
  { keyword: 'sex assignment', score: 9 },
  { keyword: 'third gender', score: 9 },
  { keyword: 'transgender', score: 9 },
  { keyword: 'transmisogyny', score: 9 },
  { keyword: 'transphobia', score: 9 },
  { keyword: 'transsexual', score: 9 },
  { keyword: 'undocumented', score: 9 },
  { keyword: 'undocumented student', score: 9 },
  { keyword: 'zir', score: 9 },
  { keyword: 'diversity', score: 8 },
  { keyword: 'AFAB/AMAB', score: 8 },
  { keyword: 'affirmative action', score: 8 },
  { keyword: 'agender', score: 8 },
  { keyword: 'anti-racist', score: 8 },
  { keyword: 'BIPOC', score: 8 },
  { keyword: 'bigender', score: 8 },
  { keyword: 'critical analysis', score: 8 },
  { keyword: 'critical media literacy', score: 8 },
  { keyword: 'demigender', score: 8 },
  { keyword: 'drag queen', score: 8 },
  { keyword: 'fluid', score: 8 },
  { keyword: 'fluidity', score: 8 },
  { keyword: 'intersex', score: 8 },
  { keyword: 'pronouns', score: 8 },
  { keyword: 'transition', score: 8 },
  { keyword: 'diversity consciousness', score: 7 },
  { keyword: 'androgyne', score: 7 },
  { keyword: 'androgynous', score: 7 },
  { keyword: 'androgyny', score: 7 },
  { keyword: 'asexual', score: 7 },
  { keyword: 'Brave Space', score: 7 },
  { keyword: 'co-option', score: 7 },
  { keyword: 'co-optation', score: 7 },
  { keyword: 'decolonize', score: 7 },
  { keyword: 'diversity', score: 7 },
  { keyword: 'diversity consciousness', score: 7 },
  { keyword: 'diversity skills', score: 7 },
  { keyword: 'dysmorphism', score: 7 },
  { keyword: 'First Nation People', score: 7 },
  { keyword: 'heteronormativity', score: 7 },
  { keyword: 'heterosexism', score: 7 },
  { keyword: 'heterosexual privilege', score: 7 },
  { keyword: 'homophobia', score: 7 },
  { keyword: 'internalized racism', score: 7 },
  { keyword: 'Latinx', score: 7 },
  { keyword: 'major bodily functions', score: 7 },
  { keyword: 'queer', score: 7 },
  { keyword: 'queer theory', score: 7 },
  { keyword: 'unisex', score: 7 },
  { keyword: 'culturally responsive pedagogy', score: 6 },
  { keyword: 'dimensions of diversity', score: 6 },
  { keyword: 'equity', score: 6 },
  { keyword: 'equity (social)', score: 6 },
  { keyword: 'ESL', score: 6 },
  { keyword: 'first generation', score: 6 },
  { keyword: 'HBCU', score: 6 },
  { keyword: 'homosexual', score: 6 },
  { keyword: 'HSI', score: 6 },
  { keyword: 'inclusion', score: 6 },
  { keyword: 'inclusive excellence', score: 6 },
  { keyword: 'inclusive language', score: 6 },
  { keyword: 'Indigenous peoples', score: 6 },
  { keyword: 'MSI', score: 6 },
  { keyword: 'pansexual', score: 6 },
  { keyword: 'equity', score: 5 },
  { keyword: 'civil rights', score: 5 },
  { keyword: 'explicit bias', score: 5 },
  { keyword: 'ethnicity', score: 5 },
  { keyword: 'ethnocentrism', score: 5 },
  { keyword: 'Euro-Centric', score: 5 },
  { keyword: 'hate crime', score: 5 },
  { keyword: 'immigrant', score: 5 },
  { keyword: 'implicit bias', score: 5 },
  { keyword: 'LGBTQIAA+', score: 5 },
  { keyword: 'questioning', score: 5 },
  { keyword: 'bias', score: 4 },
  { keyword: 'bias incident', score: 4 },
  { keyword: 'bigotry', score: 4 },
  { keyword: 'climate', score: 4 },
  { keyword: 'conscious bias', score: 4 },
  { keyword: 'discrimination', score: 4 },
  { keyword: 'harassment', score: 4 },
  { keyword: 'hegemony', score: 4 },
  { keyword: 'horizontal hostility', score: 4 },
  { keyword: 'horizontal oppression', score: 4 },
  { keyword: 'marginalize', score: 4 },
  { keyword: 'marginalization', score: 4 },
  { keyword: 'microaggression', score: 4 },
  { keyword: 'micro-insults', score: 4 },
  { keyword: 'micro-invalidation', score: 4 },
  { keyword: 'minority', score: 4 },
  { keyword: 'minority groups', score: 4 },
  { keyword: 'minorities', score: 4 },
  { keyword: 'people of color', score: 4 },
  { keyword: 'safe space', score: 4 },
  { keyword: 'same gender loving', score: 4 },
  { keyword: 'white fragility', score: 4 },
  { keyword: 'white privilege', score: 4 },
  { keyword: 'white supremacy', score: 4 },
  { keyword: 'inclusion', score: 3 },
  { keyword: 'anti‐Semitism', score: 3 },
  { keyword: 'biphobia', score: 3 },
  { keyword: 'bisexual', score: 3 },
  { keyword: 'closeted', score: 3 },
  { keyword: 'in the closet', score: 3 },
  { keyword: 'cultural humility', score: 3 },
  { keyword: 'disenfranchised', score: 3 },
  { keyword: 'fundamental attribution error', score: 3 },
  { keyword: 'gay', score: 3 },
  { keyword: 'glass ceiling', score: 3 },
  { keyword: 'identity sphere', score: 3 },
  { keyword: 'impostor syndrome', score: 3 },
  { keyword: 'in‐group bias', score: 3 },
  { keyword: 'in-groups', score: 3 },
  { keyword: 'out-groups', score: 3 },
  { keyword: 'institutional oppression', score: 3 },
  { keyword: 'invisible minority', score: 3 },
  { keyword: 'lesbian', score: 3 },
  { keyword: 'LGBT', score: 3 },
  { keyword: 'LGBTQ', score: 3 },
  { keyword: 'misogyny', score: 3 },
  { keyword: 'neocolonialization', score: 3 },
  { keyword: 'patriarchy', score: 3 },
  { keyword: 'reclaim', score: 3 },
  { keyword: 'refugee', score: 3 },
  { keyword: 'settler colonialism', score: 3 },
  { keyword: 'sexual orientation', score: 3 },
  { keyword: 'social justice', score: 2 },
  { keyword: 'ableism', score: 2 },
  { keyword: 'adverse impact', score: 2 },
  { keyword: 'advocate', score: 2 },
  { keyword: 'aromantic', score: 2 },
  { keyword: 'bicultural', score: 2 },
  { keyword: 'biracial', score: 2 },
  { keyword: 'civil union', score: 2 },
  { keyword: 'class', score: 2 },
  { keyword: 'classism', score: 2 },
  { keyword: 'coming out', score: 2 },
  { keyword: 'counter-narrative', score: 2 },
  { keyword: 'cultural appropriation', score: 2 },
  { keyword: 'cultural competence', score: 2 },
  { keyword: 'cultural encapsulation', score: 2 },
  { keyword: 'cultural fluency', score: 2 },
  { keyword: 'domination', score: 2 },
  { keyword: 'feminism', score: 2 },
  { keyword: 'gender', score: 2 },
  { keyword: 'gendered', score: 2 },
  { keyword: 'genocide', score: 2 },
  { keyword: 'gentrification', score: 2 },
  { keyword: 'heterosexual', score: 2 },
  { keyword: 'favoritism', score: 2 },
  { keyword: 'intersectionality', score: 2 },
  { keyword: 'intercultural competency', score: 2 },
  { keyword: 'intergroup conflict', score: 2 },
  { keyword: 'internalized oppression', score: 2 },
  { keyword: 'linguicism', score: 2 },
  { keyword: 'multiethnic', score: 2 },
  { keyword: 'nativism', score: 2 },
  { keyword: 'neo-liberalism', score: 2 },
  { keyword: 'people-/person-first language', score: 2 },
  { keyword: 'permanent resident', score: 2 },
  { keyword: 'prejudice', score: 2 },
  { keyword: 'race', score: 2 },
  { keyword: 'racial and ethnic identity', score: 2 },
  { keyword: 'racial equity', score: 2 },
  { keyword: 'racial profiling', score: 2 },
  { keyword: 'racism', score: 2 },
  { keyword: 'racism (cultural)', score: 2 },
  { keyword: 'racism (individual)', score: 2 },
  { keyword: 'racism (institutional)', score: 2 },
  { keyword: 'racism (internalized)', score: 2 },
  { keyword: 'racism (structural)', score: 2 },
  { keyword: 'racist policy', score: 2 },
  { keyword: 'accessibility', score: 1 },
  { keyword: 'accommodation', score: 1 },
  { keyword: 'acculturation', score: 1 },
  { keyword: 'ageism', score: 1 },
  { keyword: 'ally', score: 1 },
  { keyword: 'allyship', score: 1 },
  { keyword: 'code-switching', score: 1 },
  { keyword: 'colonialism', score: 1 },
  { keyword: 'colonization', score: 1 },
  { keyword: 'cultural landscape', score: 1 },
  { keyword: 'democracy', score: 1 },
  { keyword: 'denial', score: 1 },
  { keyword: 'disability', score: 1 },
  { keyword: 'diaspora', score: 1 },
  { keyword: 'direct threat', score: 1 },
  { keyword: 'disadvantaged', score: 1 },
  { keyword: 'domestic partner', score: 1 },
  { keyword: 'dominant culture', score: 1 },
  { keyword: 'double consciousness', score: 1 },
  { keyword: 'king', score: 1 },
  { keyword: 'elitism', score: 1 },
  { keyword: 'emotional intelligence', score: 1 },
  { keyword: 'empathy', score: 1 },
  { keyword: 'equality', score: 1 },
  { keyword: 'enculturation', score: 1 },
  { keyword: 'fundamentalism', score: 1 },
  { keyword: 'gatekeeping', score: 1 },
  { keyword: 'global competency', score: 1 },
  { keyword: 'global perspective', score: 1 },
  { keyword: 'globalization', score: 1 },
  { keyword: 'glocalization', score: 1 },
  { keyword: 'group identity', score: 1 },
  { keyword: 'justice', score: 1 },
  { keyword: 'lines of difference', score: 1 },
  { keyword: 'lookism', score: 1 },
  { keyword: 'mobility', score: 1 },
  { keyword: 'model minority', score: 1 },
  { keyword: 'multicultural', score: 1 },
  { keyword: 'multiracial', score: 1 },
  { keyword: 'naming', score: 1 },
  { keyword: 'national origin', score: 1 },
  { keyword: 'neurodiversity', score: 1 },
  { keyword: 'nondisabled', score: 1 },
  { keyword: 'non-white', score: 1 },
  { keyword: 'oppression', score: 1 },
  { keyword: 'oppression (institutionalized)', score: 1 },
  { keyword: 'oppression (internalized)', score: 1 },
  { keyword: 'overprivileged', score: 1 },
  { keyword: 'passing privilege', score: 1 },
  { keyword: 'post-racial', score: 1 },
  { keyword: 'privilege', score: 1 },
  { keyword: 'privileged group member', score: 1 },
  { keyword: 'protected status', score: 1 },
  { keyword: 'PWI', score: 1 },
  { keyword: 'pyramiding effect', score: 1 },
  { keyword: 'qualified individual', score: 1 },
  { keyword: 'rankism', score: 1 },
  { keyword: 'reasonable accommodation', score: 1 },
  { keyword: 're-fencing', score: 1 },
  { keyword: 'restorative justice', score: 1 },
  { keyword: 'saliency', score: 1 },
  { keyword: 'social inequality', score: 1 },
  { keyword: 'social justice', score: 1 },
  { keyword: 'solidarity', score: 1 },
  { keyword: 'stereotype', score: 1 },
  { keyword: 'stereotype threat', score: 1 },
  { keyword: 'structural inequality', score: 1 },
  { keyword: 'Survivor', score: 1 },
  { keyword: 'system of oppression', score: 1 },
  { keyword: 'tokenism', score: 1 },
  { keyword: 'Two Spirit', score: 1 },
  { keyword: 'unconscious bias', score: 1 },
  { keyword: 'underprivileged', score: 1 },
  { keyword: 'underrepresented communities', score: 1 },
  { keyword: 'universal design', score: 1 },
  { keyword: 'accomplice', score: 0 },
  { keyword: 'accountability', score: 0 },
  { keyword: 'active listening', score: 0 },
  { keyword: 'agency', score: 0 },
  { keyword: 'agent', score: 0 },
  { keyword: 'agnostic', score: 0 },
  { keyword: 'American', score: 0 },
  { keyword: 'assimilation', score: 0 },
  { keyword: 'at-risk', score: 0 },
  { keyword: 'autism', score: 0 },
  { keyword: 'blind', score: 0 },
  { keyword: 'capitalism', score: 0 },
  { keyword: 'categorization', score: 0 },
  { keyword: 'citizen', score: 0 },
  { keyword: 'coalition', score: 0 },
  { keyword: 'codification', score: 0 },
  { keyword: 'collusion', score: 0 },
  { keyword: 'color-blind', score: 0 },
  { keyword: 'colorism', score: 0 },
  { keyword: 'culture', score: 0 },
  { keyword: 'deaf', score: 0 },
  { keyword: 'dialogue', score: 0 },
  { keyword: 'essential functions of the job', score: 0 },
  { keyword: 'major life activities', score: 0 },
  { keyword: 'media literacy', score: 0 },
  { keyword: 'multiplicity', score: 0 },
  { keyword: 'nonviolence', score: 0 },
  { keyword: 'Pell-eligible', score: 0 },
  { keyword: 'personal identity', score: 0 },
  { keyword: 'pluralism', score: 0 },
  { keyword: 'exception-making', score: 0 },
  { keyword: 'religion', score: 0 },
  { keyword: 'religious oppression', score: 0 },
  { keyword: 'resilience', score: 0 },
  { keyword: 'respect', score: 0 },
  { keyword: 'sapiosexual', score: 0 },
  { keyword: 'scapegoating', score: 0 },
  { keyword: 'serostatus', score: 0 },
  { keyword: 'sex', score: 0 },
  { keyword: 'sexism', score: 0 },
  { keyword: 'silencing', score: 0 },
  { keyword: 'sizeism', score: 0 },
  { keyword: 'social construction', score: 0 },
  { keyword: 'social forces', score: 0 },
  { keyword: 'social identity', score: 0 },
  { keyword: 'social identity development', score: 0 },
  { keyword: 'social movement', score: 0 },
  { keyword: 'social oppression', score: 0 },
  { keyword: 'social self‐esteem', score: 0 },
  { keyword: 'social self‐view', score: 0 },
  { keyword: 'social transition', score: 0 },
  { keyword: 'socialization', score: 0 },
  { keyword: 'SOFFA', score: 0 },
  { keyword: 'spotlighting', score: 0 },
  { keyword: 'status (social status)', score: 0 },
  { keyword: 'stealth', score: 0 },
  { keyword: 'stigma', score: 0 },
  { keyword: 'stigmatization', score: 0 },
  { keyword: 'subordination', score: 0 },
  { keyword: 'substantially limiting', score: 0 },
  { keyword: 'supremacy', score: 0 },
  { keyword: 'TCU', score: 0 },
  { keyword: 'tolerance', score: 0 },
  { keyword: 'transculturation', score: 0 },
  { keyword: 'transformative learning', score: 0 },
  { keyword: 'underutilization', score: 0 },
  { keyword: 'undue hardship', score: 0 },
  { keyword: 'union', score: 0 },
  { keyword: 'UPstander', score: 0 },
  { keyword: 'upward mobility', score: 0 },
  { keyword: 'upward social mobility', score: 0 },
  { keyword: 'veteran status', score: 0 },
  { keyword: 'whiteness', score: 0 },
  { keyword: 'worldview', score: 0 },
  { keyword: 'xenophobia', score: 0 },
  { keyword: 'Yes Means Yes', score: 0 },
];